package mz.ciuem.uclinica.auth;

public enum Authorization {

	
	ROLE_AGENDAR_CONSULTA, ROLE_LISTAR_CONSULTA, ROLE_REGISTAR_PACIENTE_COMUN,
	ROLE_REGISTAR_PACIENTE_FUNC, ROLE_REGISTAR_PACIENTE_EST, ROLE_PESQUISAR_PACIENTE,
	ROLE_LISTAR_PACIENTE, ROLE_REGISTAR_SERVICO, ROLE_REGISTAR_UTILIZADOR, ROLE_LISTAR_UTILIZADOR, ROLE_REGISTAR_PERFIL,
	ROLE_LISTAR_PERFIL, ROLE_LISTAR_CONSULTAS, ROLE_LISTAR_RECIBOS, ROLE_MEDICOS, ROLE_LABORATORIOS, ROLE_CONFIGURACAO_UEM

	
}
